name: vocabcoach
description: "An app for current and willing-to-become polyglots!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  url_launcher: ^6.1.11

  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0

  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  universal_html: ^2.2.3
  cupertino_icons: ^1.0.8
  
  firebase_core: ^2.28.0
  firebase_auth: ^4.17.6
  firebase_storage: ^11.7.0
  cloud_firestore: ^4.15.7  # Added Firestore dependency
  intl: ^0.18.0  # Add this line for the intl package
  path: ^1.8.3
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2  

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/badges/
    - assets/icons/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  android_min_sdk_version: 21
