name: memorly
description: "An app for current and willing-to-become polyglots!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  url_launcher: ^6.1.11

  flutter:
    sdk: flutter
  flutter_localizations:  # ADD THIS LINE
    sdk: flutter          # ADD THIS LINE
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
 

  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  universal_html: ^2.2.3
  cupertino_icons: ^1.0.8
  
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  intl: ^0.20.2
  path: ^1.8.3
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/badges/
    - assets/icons/
flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "assets/icons/background.png" # Create a plain background image
  adaptive_icon_foreground: "assets/icons/foreground.png" # Create a foreground version
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart