// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVVV2J6qCTAVH9sA9IvhVjeTWtXyrIkFs',
    appId: '1:60132104440:web:e24c63c1163d8f7f2cc30d',
    messagingSenderId: '60132104440',
    projectId: 'memorly-2547a',
    authDomain: 'memorly-2547a.firebaseapp.com',
    storageBucket: 'memorly-2547a.firebasestorage.app',
    measurementId: 'G-X4YXWRJET9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBGeBukCCxB73XL1OM1VJr1qC2q3Ssn4E',
    appId: '1:60132104440:android:102a37813ae982892cc30d',
    messagingSenderId: '60132104440',
    projectId: 'memorly-2547a',
    storageBucket: 'memorly-2547a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEXVPd36wnFpE8OQqSUsm_EoO8QoZZGr0',
    appId: '1:60132104440:ios:b17f4b576ffb148f2cc30d',
    messagingSenderId: '60132104440',
    projectId: 'memorly-2547a',
    storageBucket: 'memorly-2547a.firebasestorage.app',
    iosBundleId: 'adaminion.memorly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEXVPd36wnFpE8OQqSUsm_EoO8QoZZGr0',
    appId: '1:60132104440:ios:b17f4b576ffb148f2cc30d',
    messagingSenderId: '60132104440',
    projectId: 'memorly-2547a',
    storageBucket: 'memorly-2547a.firebasestorage.app',
    iosBundleId: 'adaminion.memorly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVVV2J6qCTAVH9sA9IvhVjeTWtXyrIkFs',
    appId: '1:60132104440:web:d8b09866fad5ebc52cc30d',
    messagingSenderId: '60132104440',
    projectId: 'memorly-2547a',
    authDomain: 'memorly-2547a.firebaseapp.com',
    storageBucket: 'memorly-2547a.firebasestorage.app',
    measurementId: 'G-PW86N05HR4',
  );

}