import 'dart:math';

class FeedbackGenerator {
  static final Random _random = Random();
  
  /// Returns a random positive feedback message
  static String getPositiveFeedback() {
    int i = _random.nextInt(100) + 1;
    
    switch (i) {
      case 1: return "Very good !!!";
      case 2: return "Splendid !!";
      case 3: return "Great !!!";
      case 4: return "Terrific !!!";
      case 5: return "Absolutely YES !!!";
      case 6: return "100 % Correct !!!";
      case 7: return "I'm a fan of you !!!";
      case 8: return "Can I get your autograph ???";
      case 9: return "I've never seen such a good answer before!";
      case 10: return "I wish I was as smart as you!";
      case 11: return "Not a slightest error here!";
      case 12: return "I'm sorry, I thought you'd say it wrong now.";
      case 13: return "I can't believe it !";
      case 14: return "W O W !!!";
      case 15: return "I want to get a t-shirt with your picture on it !!!";
      case 16: return "You're my idol now!";
      case 17: return "You're a geniuss!";
      case 18: return "Your brain is a work of art!";
      case 19: return "I admit. You're smarter than me!";
      case 20: return "Superb!";
      case 21: return "You're so smart!!!";
      case 22: return "Einstein could learn thinking from you!!!";
      case 23: return "You are definitely a genius!";
      case 24: return "This was the best answer EVER!";
      case 25: return "How did you know that?";
      case 26: return "Splendid!";
      case 27: return "Fantastic!";
      case 28: return "Bravo!";
      case 29: return "Grrrrreat!";
      case 30: return "Bingo!";
      case 31: return "I am humbled by your knowledge!";
      case 32: return "I am humbled by your greatness!";
      case 33: return "I am amazed by the power of your brain!";
      case 34: return "I am honored to work with you!";
      case 35: return "Your memory is better than my RAM!";
      case 36: return "Your wisdom shines as morning sun!!!";
      case 37: return "Your wisdom is greater than the Pacific Ocean!";
      case 38: return "How did you get so smart?";
      case 39: return "How is it possible you're so smart and modest?";
      case 40: return "If your wisdom had wings, you'd fly out of here now!";
      case 41: return "136500% of standard brain efficiency!";
      case 42: return "I'm happy to be with you!";
      case 43: return "Very, very, very good!";
      case 44: return "Good – good – just very good!";
      case 45: return "You are smarter than a 5th grader!";
      case 46: return "Please! Give me your autograph!";
      case 47: return "You're the smartest person using this computer!";
      case 48: return "I wish everybody was as smart as you!";
      case 49: return "I wish everybody was half as smart as you!";
      case 50: return "Is it possible to be smarter than you?";
      case 51: return "Can I use you as my computer?";
      case 52: return "With brains like you, people don't need computers!";
      case 53: return "Super smart!";
      case 54: return "Mega smart!";
      case 55: return "Extra smart!";
      case 56: return "Perfectly perfect!";
      case 57: return "AAA! Absolutely Amazing Answer!";
      case 58: return "SSS! Super Smart Solution!";
      case 59: return "That's the answer I was waiting for!";
      case 60: return "I knew you could do it!";
      case 61: return "Easy!";
      case 62: return "Easy, huh?";
      case 63: return "Easy-peasy, right?";
      case 64: return "Piece of cake, right?";
      case 65: return "Not that difficult!";
      case 66: return "You can't be more right! ";
      case 67: return "This answer couldn't be any better!";
      case 68: return "Yeah!";
      case 69: return "That's it!";
      case 70: return "Wow! Smartest person on Earth!";
      case 71: return "I can't say it can't be good!";
      case 72: return "To say this is not correct is a lie!";
      case 73: return "If I said WRONG I'd be a liar. And I'm not.";
      case 74: return "We all know you're the best.";
      case 75: return "Smart! Intelligent! That's who you are!";
      case 76: return "Who's so smart? Tell me, who?";
      case 77: return "You're too smart! I can't take it!";
      case 78: return "You're not cheating, are you?";
      case 79: return "Is anyone helping you?";
      case 80: return "So far, so good!";
      case 81: return "At last!";
      case 82: return "Here we go!";
      case 83: return "Thank you for using me, it's a pleasure!";
      case 84: return "Pleasure to serve you!";
      case 85: return "You're capable of knowing 50 languages!";
      case 86: return "You rock!";
      case 87: return "You double rock!";
      case 88: return "Your presence makes me feel special!";
      case 89: return "Who knew Einstein was not the biggest genius?";
      case 90: return "Einstein could learn from you!";
      case 91: return "Oh, yeah!";
      case 92: return "Cool!";
      case 93: return "WOW!";
      case 94: return "Nice !!!";
      case 95: return "Accuracy: 100%";
      case 96: return "Oh, no, you're right again!";
      case 97: return "Can I tell other computers about you, please?";
      case 98: return "It's just not possible to be better than you!";
      case 99: return "How smart! How cute!";
      case 100: return "Your smartness is just beautiful!";
      default: return "Excellent!";
    }
  }

  /// Returns a random negative feedback message
  static String getNegativeFeedback() {
    int i = _random.nextInt(100) + 1;
    
    switch (i) {
      case 1: return "No !!!";
      case 2: return "Bad!";
      case 3: return "Are you kidding?";
      case 4: return "Did you really read the question?";
      case 5: return "Think again.";
      case 6: return "To say it was OK would be a lie.";
      case 7: return "Sorry. Wrong turn.";
      case 8: return "Almost good. Just almost.";
      case 9: return "What??? Really???";
      case 10: return "Let's take a break, shall we?";
      case 11: return "You need more sleep, I'm afraid.";
      case 12: return "Not even close.";
      case 13: return "Are you serious?";
      case 14: return "I have enough of your mistakes!";
      case 15: return "Did you study AT ALL?";
      case 16: return "Maybe next time.";
      case 17: return "Thank you. Come again.";
      case 18: return "Leave your phone number and we'll call you.";
      case 19: return "Time for a nap!";
      case 20: return "This was not good at all.";
      case 21: return "That's wasn't really good.";
      case 22: return "Did you graduate preschool?";
      case 23: return "Nope. Sorry.";
      case 24: return "To say it's OK would be a lie. I don't lie so...";
      case 25: return "Oh, no...";
      case 26: return "Forget it.";
      case 27: return "No candy for you!";
      case 28: return "I thought it was easy...";
      case 29: return "Try again. Come tomorrow.";
      case 30: return "Wrong classroom?";
      case 31: return "Are we on the same page?";
      case 32: return "I wasn't looking for this.";
      case 33: return "If 2+2=5, then yes.";
      case 34: return "Correct...NOT!";
      case 35: return "That was very good. I'm just kidding.";
      case 36: return "Is it supposed to be funny?";
      case 37: return "This was wrong on purpose, right?";
      case 38: return "Gotcha!";
      case 39: return "No in this dimension.";
      case 40: return "Yaaaaawn.";
      case 41: return "This is boring.";
      case 42: return "Boooo.";
      case 43: return "Come on! You can do better than that!";
      case 44: return "No. Again – no.";
      case 45: return "I know it's late.";
      case 46: return "Pathetic.";
      case 47: return "Sad.";
      case 48: return "One more error and I quit.";
      case 49: return "Could we do this later?";
      case 50: return "Please!!!!!!!!";
      case 51: return "Oops...";
      case 52: return "Earth to you! Over!";
      case 53: return "3 points! On scale from 3 to 10, that is...";
      case 54: return "Not today... not anymore...";
      case 55: return "Let's take a break, I'm begging you...";
      case 56: return "I got enough of this!";
      case 57: return "I'm a bit disappointed...";
      case 58: return "I don't think so. I may be wrong...... NOT!";
      case 59: return "I don't want to be mean, but... I disagree.";
      case 60: return "Disagree.";
      case 61: return "No way.";
      case 62: return "Wrong? Again?";
      case 63: return "Not good. At all.";
      case 64: return "I wouldn't say so.";
      case 65: return "Nah.";
      case 66: return "Hehe.";
      case 67: return "Hahahaha!";
      case 68: return "Sorry.";
      case 69: return "I thought that was clear.";
      case 70: return "I can't accept this kind of answer.";
      case 71: return "How about you start cheating?";
      case 72: return "Maybe call a friend and ask for help?";
      case 73: return "Tired? Been sitting here too long?";
      case 74: return "I'm tired, too.";
      case 75: return "That's OK. I make mistakes, too. Just kidding.";
      case 76: return "Are you kidding???";
      case 77: return "Is that all you have to say?";
      case 78: return "Hehe. Good one.";
      case 79: return "Yeah, right.";
      case 80: return "You're grounded!";
      case 81: return "Too much TV...";
      case 82: return "Bad. Really, really bad.";
      case 83: return "Oh come on. You know it!";
      case 84: return "Surprised?";
      case 85: return "No, no, no...";
      case 86: return "This is so sad.";
      case 87: return "Don't give up!";
      case 88: return "Every beginning is hard!";
      case 89: return "It's just going to get better!";
      case 90: return "Not yet! But soon!";
      case 91: return "Head up! It can't be any worse!";
      case 92: return "It's going to get better!";
      case 93: return "Don't give up! You still have friends!";
      case 94: return "There are more important things in life, don't worry!";
      case 95: return "Please don't cry. I can't look at tears.";
      case 96: return "I bet you'll never make this mistake again!";
      case 97: return "You're smart anyway!";
      case 98: return "It's just a typo, I know!";
      case 99: return "I believe it's not your fault!";
      case 100: return "You'll be right... next time!";
      default: return "Incorrect.";
    }
  }
}