// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnJz0kA_tBH0Fa1C1yTEfsJJSYhGHDd18',
    appId: '1:479125264130:web:d62e424da85a792293d41b',
    messagingSenderId: '479125264130',
    projectId: 'vocabcoach-49dbd',
    authDomain: 'vocabcoach-49dbd.firebaseapp.com',
    storageBucket: 'vocabcoach-49dbd.firebasestorage.app',
    measurementId: 'G-LS99G76DX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl64Qe7Qp8lbhTh0XyvLzHTfyZ283PgbM',
    appId: '1:479125264130:android:a306d49ba26a40c893d41b',
    messagingSenderId: '479125264130',
    projectId: 'vocabcoach-49dbd',
    storageBucket: 'vocabcoach-49dbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhq-VrEe1x8xb3fKE0fNLd1mxpBVJlFTo',
    appId: '1:479125264130:ios:85be48e08178dbdf93d41b',
    messagingSenderId: '479125264130',
    projectId: 'vocabcoach-49dbd',
    storageBucket: 'vocabcoach-49dbd.firebasestorage.app',
    iosBundleId: 'com.example.vocabcoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhq-VrEe1x8xb3fKE0fNLd1mxpBVJlFTo',
    appId: '1:479125264130:ios:85be48e08178dbdf93d41b',
    messagingSenderId: '479125264130',
    projectId: 'vocabcoach-49dbd',
    storageBucket: 'vocabcoach-49dbd.firebasestorage.app',
    iosBundleId: 'com.example.vocabcoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnJz0kA_tBH0Fa1C1yTEfsJJSYhGHDd18',
    appId: '1:479125264130:web:3b9be46a2ddc527293d41b',
    messagingSenderId: '479125264130',
    projectId: 'vocabcoach-49dbd',
    authDomain: 'vocabcoach-49dbd.firebaseapp.com',
    storageBucket: 'vocabcoach-49dbd.firebasestorage.app',
    measurementId: 'G-QSLXPQSK03',
  );

}